In [1]:
# Cell 1
import pandas as pd

In [2]:
# Cell 2
results = pd.read_csv('../data/results.csv')
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [3]:
# Cell 3
results.shape

(26759, 18)

In [4]:
# Cell 4
results.info()

<class 'pandas.DataFrame'>
RangeIndex: 26759 entries, 0 to 26758
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26759 non-null  int64
 1   raceId           26759 non-null  int64
 2   driverId         26759 non-null  int64
 3   constructorId    26759 non-null  int64
 4   number           26759 non-null  str
 5   grid             26759 non-null  int64
 6   position         26759 non-null  str
 7   positionText     26759 non-null  str
 8   positionOrder    26759 non-null  int64
 9   points           26759 non-null  float64
 10  laps             26759 non-null  int64
 11  time             26759 non-null  str
 12  milliseconds     26759 non-null  str
 13  fastestLap       26759 non-null  str
 14  rank             26759 non-null  str
 15  fastestLapTime   26759 non-null  str
 16  fastestLapSpeed  26759 non-null  str
 17  statusId         26759 non-null  int64
dtypes: float64(1), int64(8), str(9)
memory usage: 3.7 MB

In [5]:
results['position'].unique()

<StringArray>
[ '1',  '2',  '3',  '4',  '5',  '6',  '7',  '8', '\N',  '9', '10', '11', '12',
 '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25',
 '26', '27', '28', '29', '30', '31', '32', '33']
Length: 34, dtype: str

In [6]:
(results['position'] == '\\N').sum()

np.int64(10953)

In [7]:
results['positionOrder'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [8]:
results['positionOrder'].isnull().sum()

np.int64(0)

In [9]:
results.loc[results['position'] == '\\N', 'positionOrder'].head(10)

8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
Name: positionOrder, dtype: int64

In [10]:
drivers = pd.read_csv('../data/drivers.csv')
races = pd.read_csv('../data/races.csv')

drivers.head()
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [11]:
drivers.columns.tolist()

['driverId',
 'driverRef',
 'number',
 'code',
 'forename',
 'surname',
 'dob',
 'nationality',
 'url']

In [12]:
merged = results.merge(drivers, on='driverId', how='left')
merged.shape
merged[['resultId', 'driverId', 'forename', 'surname']].head()

   resultId  driverId  forename     surname
0         1         1     Lewis    Hamilton
1         2         2      Nick    Heidfeld
2         3         3      Nico     Rosberg
3         4         4  Fernando      Alonso
4         5         5    Heikki  Kovalainen

In [13]:
merged = merged.merge(races[['raceId', 'year', 'round', 'circuitId', 'name', 'date']], on='raceId', how='left')
merged.shape

(26759, 31)

In [14]:
merged.columns.tolist()

['resultId',
 'raceId',
 'driverId',
 'constructorId',
 'number_x',
 'grid',
 'position',
 'positionText',
 'positionOrder',
 'points',
 'laps',
 'time',
 'milliseconds',
 'fastestLap',
 'rank',
 'fastestLapTime',
 'fastestLapSpeed',
 'statusId',
 'driverRef',
 'number_y',
 'code',
 'forename',
 'surname',
 'dob',
 'nationality',
 'url',
 'year',
 'round',
 'circuitId',
 'name',
 'date']

In [15]:
constructors = pd.read_csv('../data/constructors.csv')
circuits = pd.read_csv('../data/circuits.csv')

constructors.columns.tolist()
circuits.columns.tolist()

['circuitId',
 'circuitRef',
 'name',
 'location',
 'country',
 'lat',
 'lng',
 'alt',
 'url']

In [16]:
constructors_renamed = constructors[['constructorId', 'name']].rename(columns={'name': 'constructor_name'})
circuits_renamed = circuits[['circuitId', 'name', 'location', 'country']].rename(columns={'name': 'circuit_name'})

merged = merged.merge(constructors_renamed, on='constructorId', how='left')
merged = merged.merge(circuits_renamed, on='circuitId', how='left')

In [17]:
merged.shape
merged.columns.tolist()

['resultId',
 'raceId',
 'driverId',
 'constructorId',
 'number_x',
 'grid',
 'position',
 'positionText',
 'positionOrder',
 'points',
 'laps',
 'time',
 'milliseconds',
 'fastestLap',
 'rank',
 'fastestLapTime',
 'fastestLapSpeed',
 'statusId',
 'driverRef',
 'number_y',
 'code',
 'forename',
 'surname',
 'dob',
 'nationality',
 'url',
 'year',
 'round',
 'circuitId',
 'name',
 'date',
 'constructor_name',
 'circuit_name',
 'location',
 'country']

In [18]:
merged['finished'] = merged['statusId'] == 1
merged['finished'].value_counts()

finished
False    19085
True      7674
Name: count, dtype: int64

In [19]:
status = pd.read_csv('../data/status.csv')
status.head(20)

    statusId        status
0          1      Finished
1          2  Disqualified
2          3      Accident
3          4     Collision
4          5        Engine
5          6       Gearbox
6          7  Transmission
7          8        Clutch
8          9    Hydraulics
9         10    Electrical
10        11        +1 Lap
11        12       +2 Laps
12        13       +3 Laps
13        14       +4 Laps
14        15       +5 Laps
15        16       +6 Laps
16        17       +7 Laps
17        18       +8 Laps
18        19       +9 Laps
19        20      Spun off

In [20]:
merged['finished'] = merged['position'] != '\\N'
merged['finished'].value_counts()

finished
True     15806
False    10953
Name: count, dtype: int64

In [21]:
status = pd.read_csv('../data/status.csv')
merged = merged.merge(status, on='statusId', how='left')

In [22]:
races[['raceId', 'year', 'round']].sort_values('raceId').head(20)
races[['raceId', 'year', 'round']].sort_values('raceId').tail(20)

      raceId  year  round
1105    1125  2024      5
1106    1126  2024      6
1107    1127  2024      7
1108    1128  2024      8
1109    1129  2024      9
1110    1130  2024     10
1111    1131  2024     11
1112    1132  2024     12
1113    1133  2024     13
1114    1134  2024     14
1115    1135  2024     15
1116    1136  2024     16
1117    1137  2024     17
1118    1138  2024     18
1119    1139  2024     19
1120    1140  2024     20
1121    1141  2024     21
1122    1142  2024     22
1123    1143  2024     23
1124    1144  2024     24

In [23]:
races[['raceId', 'year', 'round']].sort_values('raceId').head(20)

    raceId  year  round
0        1  2009      1
1        2  2009      2
2        3  2009      3
3        4  2009      4
4        5  2009      5
5        6  2009      6
6        7  2009      7
7        8  2009      8
8        9  2009      9
9       10  2009     10
10      11  2009     11
11      12  2009     12
12      13  2009     13
13      14  2009     14
14      15  2009     15
15      16  2009     16
16      17  2009     17
17      18  2008      1
18      19  2008      2
19      20  2008      3

In [24]:
merged_sorted = merged.sort_values(['year', 'round'])
merged_sorted[['raceId', 'year', 'round']].drop_duplicates().head(20)

       raceId  year  round
20024     833  1950      1
20045     834  1950      2
20066     835  1950      3
20099     836  1950      4
20117     837  1950      5
20131     838  1950      6
20149     839  1950      7
19850     825  1951      1
19871     826  1951      2
19904     827  1951      3
19917     828  1951      4
19940     829  1951      5
19960     830  1951      6
19982     831  1951      7
20004     832  1951      8
19639     817  1952      1
19660     818  1952      2
19693     819  1952      3
19715     820  1952      4
19735     821  1952      5

In [25]:
merged_sorted = merged.sort_values(['year', 'round']).reset_index(drop=True)

merged_sorted['recent_form'] = (
    merged_sorted.groupby('driverId')['positionOrder']
    .transform(lambda x: x.shift(1).rolling(5).mean())
)

merged_sorted[['driverId', 'year', 'round', 'positionOrder', 'recent_form']].head(20)

    driverId  year  round  positionOrder  recent_form
0        642  1950      1              1          NaN
1        786  1950      1              2          NaN
2        686  1950      1              3          NaN
3        704  1950      1              4          NaN
4        627  1950      1              5          NaN
5        619  1950      1              6          NaN
6        787  1950      1              7          NaN
7        741  1950      1              8          NaN
8        784  1950      1              9          NaN
9        778  1950      1             10          NaN
10       660  1950      1             11          NaN
11       579  1950      1             12          NaN
12       776  1950      1             13          NaN
13       669  1950      1             14          NaN
14       747  1950      1             15          NaN
15       785  1950      1             16          NaN
16       640  1950      1             17          NaN
17       589  1950      1             18          NaN
18       789  1950      1             19          NaN
19       661  1950      1             20          NaN

In [26]:
merged_sorted['recent_form'].isnull().sum()

np.int64(3149)

In [27]:
merged_sorted.shape

(26759, 38)